INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (1, 'Bañamos a tu pez', '¿Te gustaría que tus peces lucieran un aspecto limpio y brillante? ¿Te apetece mimarlos con un tratamiento de belleza? Se trata de un baño relajante y terapéutico para los peces, les ayuda a eliminar el estrés, mejorar la circulación y prevenir enfermedades. Además, el servicio de baño de peces es apto para todo tipo de peces de agua dulce o salada, y se realiza con la máxima higiene y seguridad.', 'IMGS/banyo.jfif');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (2, 'Paseamos a tu pez', '¿Te gustaría que tus peces disfrutaran de un paseo al aire libre? Este servicio es exclusivo y personalizado para aquellos que quieran dar a sus peces un cambio de aires y una aventura acuática. No lo dudes más y confía en nosotros para pasear a tus peces mientras tú te relajas o trabajas. El servicio de paseo de peces es una forma de enriquecer la vida de tus mascotas y hacerlas más felices.', 'IMGS/paseo.jfif');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (3, 'Cuidamos a tu pez', '¿Te vas de viaje y no sabes qué hacer con tus peces? ¿Te preocupa que se queden solos y sin comida? No lo dudes más y confía en nosotros para cuidar de tus peces mientras tú te vas de viaje. El servicio de guardería para peces es una forma de asegurarte de que tus mascotas estarán bien atendidas y felices.', 'IMGS/guarderia.jfif');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (4, 'Diseñamos chubasqueros', '¿Te gustaría que tus peces vistieran con estilo y comodidad? ¿Te imaginas ver a tus peces lucir unos chubasqueros originales y divertidos? Se trata de un servicio exclusivo y personalizado para los amantes de los acuarios, que quieren dar a sus peces un toque de color y personalidad. Además, es una experiencia única y divertida para tus peces, que podrán estrenar unos chubasqueros hechos a su medida y gusto, que los protegerán del frío y la lluvia, y que los harán destacar entre los demás.', 'IMGS/costurero.jfif');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (5, 'Fotografiamos a tu pez', '¿Te gustaría que tus peces tuvieran un recuerdo inolvidable de su chubasquero? ¿Te apetece mostrar a tus amigos y familiares lo guapos que están tus peces con sus prendas? Ofrecemos este servicio para que puedas tener un recuerdo inolvidable de tus mascotas acuáticas, además de ser una experiencia única y divertida, donde podrán lucir sus chubasqueros en diferentes ambientes y situaciones, y que los harán sentirse como estrellas.', 'IMGS/fotografia.jfif');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (6, 'Entrenamos a tu pez', '¿Te gustaría que tus peces aprendieran a hacer trucos y habilidades? El entrenamiento para peces es una actividad que consiste en enseñar a los peces a realizar trucos y habilidades, como saltar aros, seguir órdenes o bailar al ritmo de la música. El entrenamiento para peces tiene varios beneficios, como mejorar la inteligencia, la memoria y el aprendizaje de los peces, estimular su curiosidad y creatividad, fortalecer su vínculo con sus dueños y divertirlos.', 'IMGS/entrenamiento.jfif');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (7, 'Masaje relajante para tu pez', '¿Quieres consentir a tus peces con un relajante masaje acuático? Este servicio exclusivo ofrece un masaje suave y delicado para tus peces, utilizando técnicas de estimulación y relajación muscular. El masaje ayuda a mejorar la circulación sanguínea, aliviar el estrés y promover el bienestar general de tus peces. ¡Dales un momento de pura relajación!', 'IMGS/masaje.jpg');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (8, 'Clases de buceo para peces', '¿Quieres que tus peces descubran el fascinante mundo submarino? Ofrecemos clases de buceo exclusivas para peces. Con la ayuda de instructores profesionales, tus peces aprenderán las técnicas de buceo adecuadas y podrán explorar nuevas profundidades en un entorno seguro. Sumérgete en una aventura acuática con nuestros expertos buceadores.', 'IMGS/buceo.jpg');
INSERT INTO Servicio (idServicio, titulo, descripcion, img) VALUES (9, 'Clases de cocina para peces', '¿Quieres que tus peces se conviertan en verdaderos chefs acuáticos? Nuestro servicio de clases de cocina para peces les brinda la oportunidad de aprender a preparar deliciosos platillos acuáticos. Con la guía de nuestros expertos culinarios, tus peces aprenderán técnicas de cocción, combinación de sabores y presentación de alimentos acuáticos. Descubrirán nuevas recetas y se divertirán explorando el arte culinario submarino. ¡Prepara sus paladares para una experiencia gastronómica única!', 'IMGS/cocina.jpg');


